package cn.tradewin.angular.persist.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.first_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.etype
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private Byte etype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ecom
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private Integer ecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.dept_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private Byte deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.job_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    private String jobId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.first_name
     *
     * @return the value of account.first_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.first_name
     *
     * @param firstName the value for account.first_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_name
     *
     * @return the value of account.last_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_name
     *
     * @param lastName the value for account.last_name
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile
     *
     * @return the value of account.mobile
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile
     *
     * @param mobile the value for account.mobile
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.etype
     *
     * @return the value of account.etype
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public Byte getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.etype
     *
     * @param etype the value for account.etype
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setEtype(Byte etype) {
        this.etype = etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ecom
     *
     * @return the value of account.ecom
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public Integer getEcom() {
        return ecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ecom
     *
     * @param ecom the value for account.ecom
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setEcom(Integer ecom) {
        this.ecom = ecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.dept_id
     *
     * @return the value of account.dept_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public Byte getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.dept_id
     *
     * @param deptId the value for account.dept_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setDeptId(Byte deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.job_id
     *
     * @return the value of account.job_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.job_id
     *
     * @param jobId the value for account.job_id
     *
     * @mbggenerated Tue Mar 10 13:30:52 JST 2015
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
}