package cn.tradewin.angular.persist.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.sname
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.owner
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    private String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.sname
     *
     * @return the value of department.sname
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.sname
     *
     * @param sname the value for department.sname
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.owner
     *
     * @return the value of department.owner
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.owner
     *
     * @param owner the value for department.owner
     *
     * @mbggenerated Fri Mar 13 08:57:03 JST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }
}